In [1]:
# Must be included at the beginning of each new notebook. Remember to change the app name.
import findspark
findspark.init('/home/ubuntu/spark-3.2.1-bin-hadoop2.7')
import pyspark
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('basics').getOrCreate()
!pip install openpyxl

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/ubuntu/spark-3.2.1-bin-hadoop2.7/jars/spark-unsafe_2.12-3.2.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
24/05/19 06:32:41 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in /home/ubuntu/.local/lib/python3.10/site-packages (3.1.2)
Requirement already satisfied: et-xmlfile in /home/ubuntu/.local/lib/python3.10/site-packages (from openpyxl) (1.1.0)

In [7]:
import pandas as pd
from pyspark.sql.functions import col, count, isnan, when

# get data
total_data = 'world-surface.xlsx'
developed_data = 'Developed.xlsx'
developing_data = 'Developing.xlsx'

df_pandas = pd.read_excel(total_data)
df_developed_pandas = pd.read_excel(developed_data)
df_developing_pandas = pd.read_excel(developing_data)

# pre
df_pandas['Country'] = df_pandas['Country'].astype(str)

# convert pandas DataFrame into Spark DataFrame
df_spark = spark.createDataFrame(df_pandas)
df_developed_spark = spark.createDataFrame(df_developed_pandas)
df_developing_spark = spark.createDataFrame(df_developing_pandas)

# explore data
df_spark.printSchema()
df_spark.describe().show()
df_developed_spark.describe().show()
df_developing_spark.describe().show()

# null
null_counts = df_spark.select([count(when(isnan(c) | col(c).isNull(), c)).alias(c) for c in df_spark.columns])

# total
total_count = df_spark.count()

# couunt of non-null
non_null_counts = null_counts.select([(total_count - col(c)).alias(c) for c in null_counts.columns])

# type
data_types = df_spark.dtypes

# null count table
summary_table = non_null_counts.toPandas().transpose().reset_index()
summary_table.columns = ['Column', 'Non-Null Count']
null_counts_pd = null_counts.toPandas().transpose().reset_index()
null_counts_pd.columns = ['Column', 'Null Count']
summary_table = summary_table.merge(null_counts_pd, on='Column')
summary_table['Data Type'] = [dtype for _, dtype in data_types]

print(summary_table)

root
 |-- Country: string (nullable = true)
 |-- GDP: double (nullable = true)
 |-- Gross primary education enrollment (%): double (nullable = true)
 |-- Gross tertiary education enrollment (%): double (nullable = true)
 |-- Out of pocket health expenditure: double (nullable = true)
 |-- Physicians per thousand: double (nullable = true)
 |-- Density\n(P/Km2): double (nullable = true)
 |-- Fertility Rate: double (nullable = true)
 |-- Population: double (nullable = true)
 |-- Urban_population: double (nullable = true)
 |-- Unemployment rate: double (nullable = true)
 |-- Population: Labor force participation (%): double (nullable = true)
 |-- CPI: double (nullable = true)
 |-- Tax revenue (%): double (nullable = true)
 |-- Total tax rate: double (nullable = true)

+-------+-----------+-----------+--------------------------------------+---------------------------------------+--------------------------------+-----------------------+----------------+--------------+----------+----------------+-----------------+-----------------------------------------+-----+---------------+--------------+
|summary|    Country|        GDP|Gross primary education enrollment (%)|Gross tertiary education enrollment (%)|Out of pocket health expenditure|Physicians per thousand|Density\n(P/Km2)|Fertility Rate|Population|Urban_population|Unemployment rate|Population: Labor force participation (%)|  CPI|Tax revenue (%)|Total tax rate|
+-------+-----------+-----------+--------------------------------------+---------------------------------------+--------------------------------+-----------------------+----------------+--------------+----------+----------------+-----------------+-----------------------------------------+-----+---------------+--------------+
|  count|        200|        200|                                   200|                                    200|                             200|                    200|             200|           200|       200|             200|              200|                                      200|  200|            200|           200|
|   mean|        NaN|        NaN|                                   NaN|                                    NaN|                             NaN|                    NaN|             NaN|           NaN|       NaN|             NaN|              NaN|                                      NaN|  NaN|            NaN|           NaN|
| stddev|       null|        NaN|                                   NaN|                                    NaN|                             NaN|                    NaN|             NaN|           NaN|       NaN|             NaN|              NaN|                                      NaN|  NaN|            NaN|           NaN|
|    min|Afghanistan|4.7271463E7|                   0.13183071150490314|                                  0.008|                           0.002|                   0.01|             2.0|          0.98|     0.631|        3.202778|           9.0E-4|                                    0.101|99.03|            0.0|        0.0204|
|    max|        nan|        NaN|                                   NaN|                                    NaN|                             NaN|                    NaN|             NaN|           NaN|       NaN|             NaN|              NaN|                                      NaN|  NaN|            NaN|           NaN|
+-------+-----------+-----------+--------------------------------------+---------------------------------------+--------------------------------+-----------------------+----------------+--------------+----------+----------------+-----------------+-----------------------------------------+-----+---------------+--------------+

+-------+------------+-------------+--------------------------------------+---------------------------------------+--------------------------------+-----------------------+------------------+--------------+--------------------+----------------+-----------------+-----------------------------------------+-----+---------------+--------------+------------+
|summary|     Country|          GDP|Gross primary education enrollment (%)|Gross tertiary education enrollment (%)|Out of pocket health expenditure|Physicians per thousand|  Density\n(P/Km2)|Fertility Rate|          Population|Urban_population|Unemployment rate|Population: Labor force participation (%)|  CPI|Tax revenue (%)|Total tax rate|Is_Developed|
+-------+------------+-------------+--------------------------------------+---------------------------------------+--------------------------------+-----------------------+------------------+--------------+--------------------+----------------+-----------------+-----------------------------------------+-----+---------------+--------------+------------+
|  count|          49|           49|                                    49|                                     49|                              49|                     49|                49|            49|                  49|              49|               49|                                       49|   49|             49|            49|          49|
|   mean|        null|          NaN|                                   NaN|                                    NaN|                             NaN|                    NaN| 917.2244897959183|           NaN|2.3412055509387758E7|             NaN|              NaN|                                      NaN|  NaN|            NaN|           NaN|         1.0|
| stddev|        null|          NaN|                                   NaN|                                    NaN|                             NaN|                    NaN|3900.2208552065044|           NaN| 5.156923351686998E7|             NaN|              NaN|                                      NaN|  NaN|            NaN|           NaN|         0.0|
|    min|     Andorra|1.637931034E9|                                 0.852|                                  0.179|                            0.06|                   1.61|                 3|          0.98|               0.631|       35.126413|           9.0E-4|                                    0.101|99.03|          0.001|        0.0458|           1|
|    max|Vatican City|          NaN|                                   NaN|                                    NaN|                             NaN|                    NaN|             26337|           NaN|        3.28239523E8|             NaN|              NaN|                                      NaN|  NaN|            NaN|           NaN|           1|
+-------+------------+-------------+--------------------------------------+---------------------------------------+--------------------------------+-----------------------+------------------+--------------+--------------------+----------------+-----------------+-----------------------------------------+-----+---------------+--------------+------------+

+-------+-----------+-----------+--------------------------------------+---------------------------------------+--------------------------------+-----------------------+------------------+--------------+----------+----------------+-----------------+-----------------------------------------+-----+---------------+--------------+------------+
|summary|    Country|        GDP|Gross primary education enrollment (%)|Gross tertiary education enrollment (%)|Out of pocket health expenditure|Physicians per thousand|  Density\n(P/Km2)|Fertility Rate|Population|Urban_population|Unemployment rate|Population: Labor force participation (%)|  CPI|Tax revenue (%)|Total tax rate|Is_Developed|
+-------+-----------+-----------+--------------------------------------+---------------------------------------+--------------------------------+-----------------------+------------------+--------------+----------+----------------+-----------------+-----------------------------------------+-----+---------------+--------------+------------+
|  count|        145|        145|                                   145|                                    145|                             145|                    145|               145|           145|       145|             145|              145|                                      145|  145|            145|           145|         145|
|   mean|       null|        NaN|                                   NaN|                                    NaN|                             NaN|                    NaN| 168.2551724137931|           NaN|       NaN|             NaN|              NaN|                                      NaN|  NaN|            NaN|           NaN|         0.0|
| stddev|       null|        NaN|                                   NaN|                                    NaN|                             NaN|                    NaN|289.33625620908305|           NaN|       NaN|             NaN|              NaN|                                      NaN|  NaN|            NaN|           NaN|         0.0|
|    min|Afghanistan|4.7271463E7|                                 0.234|                                  0.008|                           0.002|                   0.01|                 2|          1.26|     0.688|        3.202778|           0.0047|                                    0.144|99.55|            0.0|        0.0204|           0|
|    max|   Zimbabwe|        NaN|                                   NaN|                                    NaN|                             NaN|                    NaN|              2239|           NaN|       NaN|             NaN|              NaN|                                      NaN|  NaN|            NaN|           NaN|           0|
+-------+-----------+-----------+--------------------------------------+---------------------------------------+--------------------------------+-----------------------+------------------+--------------+----------+----------------+-----------------+-----------------------------------------+-----+---------------+--------------+------------+

                                       Column  Non-Null Count  Null Count  \
0                                     Country             199           1
1                                         GDP             197           3
2      Gross primary education enrollment (%)             192           8
3     Gross tertiary education enrollment (%)             187          13
4            Out of pocket health expenditure             192           8
5                     Physicians per thousand             192           8
6                            Density\n(P/Km2)             199           1
7                              Fertility Rate             192           8
8                                  Population             198           2
9                            Urban_population             194           6
10                          Unemployment rate             180          20
11  Population: Labor force participation (%)             180          20
12                                        CPI             182          18
13                            Tax revenue (%)             173          27
14                             Total tax rate             187          13

   Data Type
0     string
1     double
2     double
3     double
4     double
5     double
6     double
7     double
8     double
9     double
10    double
11    double
12    double
13    double
14    double